name: Gettext Updates
on:
  push:
    branches: [main]

jobs:
  gettext_template:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Update Translation Files
      uses: elementary/actions/gettext-template@main
      env:
        GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
